Выполнение заданий по проекту 4го спринта
LununPavel/Sprint_4 pull request #1
Opened 2023-08-13 14:44 UTC by LununPavel

Прошу ревью

2023-08-15 21:03 UTC, kadirovgm requested changes

2023-08-15 21:03 UTC, kadirovgm commented on conftest.py
> +def driver():
отлично!

2023-08-15 21:03 UTC, kadirovgm commented on pages/base_page.py
> +class BasePage:
Отлично! кажется ты правильно понял консепцию POM и базового класса BasePage

класс BasePage - это такой родительский класс, в котором содержатся общие методы, такие как: клик по определенному элементу, скролл к определенному элементу, ожидание определенного элемента, изменение табов итд.

То есть эти методы не привязаны к определенной странице, и могут быть переиспользованы в любой POM-странице, стоит сюда добавить именно такие методы.

2023-08-15 21:03 UTC, kadirovgm commented on pages/ya_scooter_main_page.py
> +
отлично!

2023-08-15 21:03 UTC, kadirovgm commented on pages/ya_scooter_order_page.py
> +    def enter_text(self, locator, text):
нужно исправить: кажется это метод базового класса BasePage

2023-08-15 21:03 UTC, kadirovgm commented on tests/test_ya_scooter_main_page.py
> +    def test_accordion_answer_1(self, driver):
нужно исправить: не стоит писать столько одинаковых строк кода, так как все эти тесты по сути идентичны, и меняется только проверяемый вопрос, то здесь уместно воспользоваться параметризацией

на вход можно передавать номер вопроса и ожидаемый ответ на нее

2023-08-15 21:03 UTC, kadirovgm commented on tests/test_ya_scooter_main_page.py
> +               'Сутки — 400 рублей. Оплата курьеру — наличными или картой.'
нужно исправить: такие статичные тестовые данные не стоит держать в коде тестов, лучше вынести отдельно, например как список в data.py

тестовые статичные данные лучше выносить в отдельный файл типа [data.py](http://data.py/) или [urls.py](http://urls.py/)
Это нужно для легкой поддержке проекта и переиспользовании тестовых данных, мы должны стремиться к тому, чтобы разделять код и тестовые данные, тем самым избегая повторений.

2023-08-15 21:03 UTC, kadirovgm commented on tests/test_ya_scooter_main_page.py
> +        ya_scooter_main_page.go_to_site(Urls.url_main_page)
супер! молодец, что Urls вынес в отдельный файл, по такому же принципу нужно поступать и с ожидаемыми ответами

2023-08-15 21:03 UTC, kadirovgm commented on tests/test_ya_scooter_main_page.py
> +        time.sleep(5)
нужно исправить: не стоит прибегать к таким видам явного ожидания как sleep, это может привести к увеличению времени прохождения теста

Существуют более удобные методы, которые помогут написать код, ожидающий ровно столько, сколько необходимо. WebDriverWait в комбинации с ExpectedCondition является одним из таких способов:

```
element = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.ID, "myDynamicElement"))
    )
```

2023-08-15 21:03 UTC, kadirovgm commented on tests/test_ya_scooter_main_page.py
> +        assert ya_scooter_main_page.check_current_url() == "https://dzen.ru/?yredirect=true"
можно лучше: проверка того, что URL поменялся на <url> не гарантирует, что страница прогрузилась, поэтому стоит ориентироваться на какие-либо элементы страницы, чекать, что они появились и отображаются корректно

2023-08-15 21:03 UTC, kadirovgm commented on tests/test_ya_scooter_order_page.py
> +        ya_scooter_order_page.enter_on_button(LocatorMainYaScooterPage.ORDER_BUTTON_IN_HEADER)
можно лучше: для того, чтобы в тестах не вызывать каждый метод для заполнения предлагаю создать метод POM страницы, например fill_order_data, который будет внутри себя вызвывать все эти маленькие методы, нам нужно скоращать тело теста

2023-08-15 21:03 UTC, kadirovgm commented on tests/test_ya_scooter_order_page.py
> +        ya_scooter_order_page.enter_on_button(LocatorMainYaScooterPage.ORDER_BUTTON_IN_HEADER)
нужно исправить: еще один аргумент, к локаторам стоти обращаться внутри методов POM страницы, так что этого точно стоит делать

2023-08-16 17:50 UTC, LununPavel commented on pages/ya_scooter_order_page.py
> +    def enter_text(self, locator, text):
исправлено

2023-08-16 17:50 UTC, LununPavel commented on tests/test_ya_scooter_main_page.py
> +    def test_accordion_answer_1(self, driver):
исправлено

2023-08-16 17:50 UTC, LununPavel commented on tests/test_ya_scooter_main_page.py
> +               'Сутки — 400 рублей. Оплата курьеру — наличными или картой.'
исправлено

2023-08-16 17:50 UTC, LununPavel commented on tests/test_ya_scooter_main_page.py
> +        time.sleep(5)
исправлено

2023-08-16 17:51 UTC, LununPavel commented on tests/test_ya_scooter_main_page.py
> +        assert ya_scooter_main_page.check_current_url() == "https://dzen.ru/?yredirect=true"
исправлено

2023-08-16 17:52 UTC, LununPavel commented on tests/test_ya_scooter_order_page.py
> +        ya_scooter_order_page.enter_on_button(LocatorMainYaScooterPage.ORDER_BUTTON_IN_HEADER)
если все правильно понял, то по двум замечаниям тоже исправлено

2023-08-16 20:59 UTC, kadirovgm approved these changes

2023-08-16 20:59 UTC, kadirovgm commented on pages/ya_scooter_order_page.py
> +
отлично!

2023-08-16 20:59 UTC, kadirovgm commented on tests/test_ya_scooter_order_page.py
> +
тут все супер стало!

2023-08-16 20:59 UTC, kadirovgm commented on tests/test_ya_scooter_order_page.py
> +
отлично!

2023-08-16 20:59 UTC, kadirovgm commented on tests/test_ya_scooter_main_page.py
> +                             [
получилось костыльно, но логику ты понял!

2023-08-17 10:03 UTC, LununPavel commented on tests/test_ya_scooter_main_page.py
> +                             [
@kadirovgm спасибо, что проверил мою работу и понятно указывал на ошибки)
Если есть возможность, можешь подсказать, как лучше в таком случае использовать параметризацию, чтобы не было костылей?

2023-08-31 08:28 UTC, merged